// apps/web/src/components/ui/checkbox.tsx
'use client'

import * as CheckboxPrimitive from '@radix-ui/react-checkbox'
import { Check } from 'lucide-react'
import * as React from 'react'

import { cn } from '@/lib/utils'

const Checkbox = React.forwardRef<
 React.ElementRef<typeof CheckboxPrimitive.Root>,
 React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
 <CheckboxPrimitive.Root
 ref={ref}
 className={cn(
 'grid place-content-center peer h-4 w-4 shrink-0 border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
 className,
 )}
 {...props}
 >
 <CheckboxPrimitive.Indicator className={cn('grid place-content-center text-current')}>
 <Check className="h-4 w-4" />
 </CheckboxPrimitive.Indicator>
 </CheckboxPrimitive.Root>
))
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export { Checkbox }

// apps/web/src/lib/components/ui/checkbox/checkbox.svelte
<script lang="ts">
	import Check from "lucide-svelte/icons/check";
	import Minus from "lucide-svelte/icons/minus";
	import { cn } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		checked = $bindable(false),
		indeterminate = $bindable(false),
		class: className,
		disabled = false,
		required = false,
		name = "",
		id = "",
		...restProps
	}: {
		ref?: HTMLButtonElement | null;
		checked?: boolean | "indeterminate";
		indeterminate?: boolean;
		class?: string;
		disabled?: boolean;
		required?: boolean;
		name?: string;
		id?: string;
		[key: string]: any;
	} = $props();

	function toggle() {
		if (disabled) return;
		if (checked === "indeterminate" || indeterminate) {
			checked = true;
			indeterminate = false;
		} else {
			checked = !checked;
		}
	}
</script>

<button
	bind:this={ref}
	type="button"
	role="checkbox"
	aria-checked={indeterminate
		? "mixed"
		: checked === "indeterminate"
			? "mixed"
			: checked}
	aria-required={required}
	{disabled}
	{id}
	class={cn(
		"border-primary ring-offset-background focus-visible:ring-ring peer box-content size-4 shrink-0 rounded-sm border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
		checked || indeterminate
			? "bg-primary text-primary-foreground"
			: "bg-background",
		className,
	)}
	onclick={toggle}
	{...restProps}
>
	<div class="flex size-4 items-center justify-center text-current">
		{#if indeterminate}
			<Minus class="size-3.5" />
		{:else if checked}
			<Check class="size-3.5" />
		{/if}
	</div>
</button>

<input
	type="checkbox"
	checked={checked === "indeterminate" ? false : checked}
	{indeterminate}
	{disabled}
	{required}
	{name}
	{id}
	class="sr-only"
	tabindex="-1"
/>
