// frontend/src/routes/admin/users/+page.svelte
<script lang="ts">
    import * as Breadcrumb from "$lib/components/ui/breadcrumb/index.js";
    import { Separator } from "$lib/components/ui/separator/index.js";
    import * as Sidebar from "$lib/components/ui/sidebar/index.js";
    import { Input } from "$lib/components/ui/input";
    import { Button } from "$lib/components/ui/button";
    import Search from "lucide-svelte/icons/search";
    import Plus from "lucide-svelte/icons/plus";
    import type { AdminUser } from "$lib/models/users";
    import { listUsersAPI, updateUserStatusAPI } from "$lib/api/admin";

    let searchQuery = $state("");
    let users = $state<AdminUser[]>([]);
    let isLoading = $state(true);
    let error = $state<string | null>(null);
    let statusUpdateLoading = $state<string | null>(null);

    loadUsers();

    async function loadUsers() {
        try {
            isLoading = true;
            error = null;
            const response = await listUsersAPI();
            users = response.users;
        } catch (e: any) {
            error = e.message || "Failed to load users";
            console.error("Load error:", e);
            users = [];
        } finally {
            isLoading = false;
        }
    }

    async function toggleUserStatus(userId: string, currentStatus: boolean) {
        try {
            statusUpdateLoading = userId;
            await updateUserStatusAPI(userId, { active: !currentStatus });
            // Reload users to get updated data
            await loadUsers();
        } catch (e: any) {
            error = e.message || "Failed to update user status";
            console.error("Status update error:", e);
        } finally {
            statusUpdateLoading = null;
        }
    }

    function formatDate(dateString: string) {
        return new Date(dateString).toLocaleString();
    }
</script>

<header class="flex h-16 shrink-0 items-center gap-2">
    <div class="flex items-center gap-2 px-4 w-full justify-between">
        <div class="flex items-center gap-2">
            <Sidebar.Trigger class="-ml-1" />
            <Separator orientation="vertical" class="mr-2 h-4" />
            <Breadcrumb.Root>
                <Breadcrumb.List>
                    <Breadcrumb.Item>
                        <Breadcrumb.Link href="/admin">Admin</Breadcrumb.Link>
                    </Breadcrumb.Item>
                    <Breadcrumb.Separator />
                    <Breadcrumb.Item>
                        <Breadcrumb.Page>Users</Breadcrumb.Page>
                    </Breadcrumb.Item>
                </Breadcrumb.List>
            </Breadcrumb.Root>
        </div>
        <div class="flex items-center gap-2">
            <div class="relative">
                <Search
                    class="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500"
                />
                <Input
                    bind:value={searchQuery}
                    placeholder="Search users..."
                    class="pl-9 w-[250px]"
                />
            </div>
            <Button>
                <Plus class="mr-2 h-4 w-4" />
                <span>Add User</span>
            </Button>
        </div>
    </div>
</header>
<div class="p-4">
    {#if error}
        <div class="mb-4 p-2 text-sm text-red-600 bg-red-50 rounded-md">
            {error}
        </div>
    {/if}

    {#if isLoading}
        <div class="flex justify-center p-8">
            <div
                class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"
            ></div>
        </div>
    {:else}
        <div class="rounded-lg border bg-card text-card-foreground shadow-sm">
            {#if users.length === 0}
                <div class="p-8 text-center text-gray-500">No users found</div>
            {:else}
                <table class="w-full">
                    <thead>
                        <tr
                            class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                        >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Name</th
                            >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Email</th
                            >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Provider</th
                            >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Role</th
                            >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Status</th
                            >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Created</th
                            >
                            <th
                                class="h-12 px-4 text-left align-middle font-medium"
                                >Actions</th
                            >
                        </tr>
                    </thead>
                    <tbody>
                        {#each users as user (user.id)}
                            <tr
                                class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                            >
                                <td class="p-4">{user.name}</td>
                                <td class="p-4">{user.email}</td>
                                <td class="p-4">{user.provider}</td>
                                <td class="p-4">
                                    {#if user.accesses}
                                        <div class="flex gap-1">
                                            {#each user.accesses as access}
                                                <span
                                                    class="inline-flex items-center rounded-full px-2 py-1 text-xs font-medium bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-600/20"
                                                >
                                                    {access}
                                                </span>
                                            {/each}
                                        </div>
                                    {/if}
                                </td>
                                <td class="p-4">
                                    <button
                                        class="inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ring-1 ring-inset"
                                        class:bg-green-50={user.isActive}
                                        class:text-green-700={user.isActive}
                                        class:ring-green-600={user.isActive}
                                        class:bg-red-50={!user.isActive}
                                        class:text-red-700={!user.isActive}
                                        class:ring-red-600={!user.isActive}
                                        class:opacity-50={statusUpdateLoading ===
                                            user.id}
                                        disabled={statusUpdateLoading ===
                                            user.id}
                                        onclick={() =>
                                            toggleUserStatus(
                                                user.id,
                                                user.isActive,
                                            )}
                                    >
                                        {#if statusUpdateLoading === user.id}
                                            <span
                                                class="inline-block animate-spin mr-1"
                                                >⟳</span
                                            >
                                        {/if}
                                        {user.isActive ? "Active" : "Inactive"}
                                    </button>
                                </td>
                                <td class="p-4">{formatDate(user.createdAt)}</td
                                >
                                <td class="p-4">
                                    <Button variant="ghost" size="sm"
                                        >Edit</Button
                                    >
                                </td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            {/if}
        </div>
    {/if}
</div>

// apps/web/src/routes/dashboard/admin/users.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createFileRoute, Link } from '@tanstack/react-router'
import { ChevronDown, ChevronUp, Search, Shield, ShieldOff, UserCheck, UserX } from 'lucide-react'
import { useState } from 'react'
import { api } from '#/lib/api'
import { cn } from '@/lib/utils'

interface AdminUser {
 id: string
 email: string
 name: string
 provider: string
 isActive: boolean
 accesses: string[] | null
 createdAt: string
}

export const Route = createFileRoute('/dashboard/admin/users')({ component: AdminUsersPage })

function ProviderBadge({ provider }: { provider: string }) {
 return (
 <span className="rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
 {provider}
 </span>
 )
}

function StatusToggle({ user, onToggle, isPending }: { user: AdminUser; onToggle: () => void; isPending: boolean }) {
 return (
 <button
 onClick={onToggle}
 disabled={isPending}
 className={cn(
 'flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-semibold transition-opacity hover:opacity-80 disabled:opacity-50',
 user.isActive
 ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'
 : 'border-destructive/30 bg-destructive/10 text-destructive',
 )}
 >
 {user.isActive ? (
 <>
 <UserCheck className="h-3 w-3" /> Active
 </>
 ) : (
 <>
 <UserX className="h-3 w-3" /> Banned
 </>
 )}
 </button>
 )
}

type SortField = 'name' | 'email' | 'provider' | 'createdAt'

function AdminUsersPage() {
 const queryClient = useQueryClient()
 const [search, setSearch] = useState('')
 const [sortField, setSortField] = useState<SortField>('createdAt')
 const [sortAsc, setSortAsc] = useState(false)

 const { data, isLoading } = useQuery({
 queryKey: ['admin', 'users'],
 queryFn: () => api.get<{ users: AdminUser[] }>('/api/admin/users'),
 })

 const toggleStatus = useMutation({
 mutationFn: ({ id, active }: { id: string; active: boolean }) =>
 api.put(`/api/admin/users/${id}/status`, { active }),
 onSuccess: () => queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }),
 })

 const toggleAdmin = useMutation({
 mutationFn: ({ id, accesses }: { id: string; accesses: string[] }) =>
 api.put(`/api/admin/users/${id}/accesses`, { accesses }),
 onSuccess: () => queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }),
 })

 function toggleSort(field: SortField) {
 if (sortField === field) setSortAsc((v) => !v)
 else {
 setSortField(field)
 setSortAsc(true)
 }
 }

 const users = (data?.users ?? [])
 .filter((u) => {
 const q = search.toLowerCase()
 return !q || u.name.toLowerCase().includes(q) || u.email.toLowerCase().includes(q)
 })
 .sort((a, b) => {
 let cmp = 0
 if (sortField === 'name') cmp = a.name.localeCompare(b.name)
 else if (sortField === 'email') cmp = a.email.localeCompare(b.email)
 else if (sortField === 'provider') cmp = a.provider.localeCompare(b.provider)
 else cmp = new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
 return sortAsc ? cmp : -cmp
 })

 function SortIcon({ field }: { field: SortField }) {
 if (sortField !== field) return null
 return sortAsc ? <ChevronUp className="h-3 w-3 inline ml-0.5" /> : <ChevronDown className="h-3 w-3 inline ml-0.5" />
 }

 return (
 <div className="mx-auto max-w-5xl space-y-4">
 {/* Header */}
 <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
 <div>
 <h1 className="text-sm font-semibold">Users</h1>
 <p className="text-xs text-muted-foreground">{data?.users.length ?? 0} registered accounts</p>
 </div>

 <div className="flex items-center gap-2 border bg-background px-2.5 py-1.5 w-full sm:w-56">
 <Search className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
 <input
 value={search}
 onChange={(e) => setSearch(e.target.value)}
 placeholder="Search by name or email…"
 className="flex-1 bg-transparent text-xs outline-none placeholder:text-muted-foreground"
 />
 </div>
 </div>

 {/* Table */}
 <div className="border overflow-hidden">
 <div className="overflow-x-auto">
 <div className="min-w-[560px]">
 <div className="grid grid-cols-[1fr_1fr_auto_auto_auto_auto] gap-3 border-b bg-muted/30 px-4 py-2.5 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
 <button className="text-left hover:text-foreground transition-colors" onClick={() => toggleSort('name')}>
 Name <SortIcon field="name" />
 </button>
 <button className="text-left hover:text-foreground transition-colors" onClick={() => toggleSort('email')}>
 Email <SortIcon field="email" />
 </button>
 <button
 className="hidden sm:block text-left hover:text-foreground transition-colors"
 onClick={() => toggleSort('provider')}
 >
 Provider <SortIcon field="provider" />
 </button>
 <span>Status</span>
 <span>Role</span>
 <button
 className="hidden sm:block text-left hover:text-foreground transition-colors"
 onClick={() => toggleSort('createdAt')}
 >
 Joined <SortIcon field="createdAt" />
 </button>
 </div>

 <div className="divide-y">
 {isLoading ? (
 [...Array(5)].map((_, i) => (
 <div key={i} className="grid grid-cols-[1fr_1fr_auto_auto_auto_auto] gap-3 px-4 py-3 animate-pulse">
 <div className="h-3.5 rounded-full bg-muted" />
 <div className="h-3.5 rounded-full bg-muted" />
 <div className="h-5 w-16 rounded-full bg-muted" />
 <div className="h-5 w-16 rounded-full bg-muted" />
 <div className="h-5 w-8 rounded-full bg-muted" />
 <div className="h-3.5 w-20 rounded-full bg-muted" />
 </div>
 ))
 ) : users.length === 0 ? (
 <p className="px-4 py-8 text-center text-xs text-muted-foreground">No users found</p>
 ) : (
 users.map((user) => {
 const isSuperadmin = user.accesses?.includes('superadmin')
 return (
 <div
 key={user.id}
 className="grid grid-cols-[1fr_1fr_auto_auto_auto_auto] items-center gap-3 px-4 py-3 hover:bg-muted/30 transition-colors"
 >
 <div className="min-w-0">
 <Link
 to="/dashboard/admin/users/$userId"
 params={{ userId: user.id }}
 className="truncate text-xs font-medium hover:text-primary transition-colors"
 >
 {user.name}
 </Link>
 </div>
 <p className="truncate text-xs text-muted-foreground">{user.email}</p>
 <div className="hidden sm:block">
 <ProviderBadge provider={user.provider} />
 </div>
 <StatusToggle
 user={user}
 isPending={toggleStatus.isPending}
 onToggle={() => toggleStatus.mutate({ id: user.id, active: !user.isActive })}
 />
 <button
 onClick={() =>
 toggleAdmin.mutate({
 id: user.id,
 accesses: isSuperadmin ? ['user'] : ['superadmin', 'user'],
 })
 }
 disabled={toggleAdmin.isPending}
 title={isSuperadmin ? 'Remove admin' : 'Make admin'}
 className={cn(
 'flex items-center justify-center h-6 w-6 border transition-opacity hover:opacity-80 disabled:opacity-50',
 isSuperadmin
 ? 'border-primary/30 bg-primary/10 text-primary'
 : 'border-border bg-muted text-muted-foreground',
 )}
 >
 {isSuperadmin ? <Shield className="h-3 w-3" /> : <ShieldOff className="h-3 w-3" />}
 </button>
 <p className="hidden sm:block text-[11px] text-muted-foreground whitespace-nowrap">
 {new Date(user.createdAt).toLocaleDateString(undefined, {
 month: 'short',
 day: 'numeric',
 year: 'numeric',
 })}
 </p>
 </div>
 )
 })
 )}
 </div>
 </div>
 </div>
 </div>
 </div>
 )
}
